#!/usr/bin/env python
"""
Usage:
    make-logo <ep_num> <palette_name> <idx_ext> <idx_int> <idx_txt>

Example:
    ./make-logo 7 'casual with skirt' 1 2 0
"""

import docopt
import os
import requests
import string

def tex_document(episode, extcolor, intcolor, txtcolor):
    lines = [r'\documentclass[tikz]{standalone}',
             r'\usepackage{tikz}',
             r'\usepackage{fontspec}',
             r'\setmainfont{Inconsolata}',
             r'\begin{document}',
             r'\definecolor{colext}{HTML}{%s}' % extcolor,
             r'\definecolor{colint}{HTML}{%s}' % intcolor,
             r'\definecolor{coltxt}{HTML}{%s}' % txtcolor,
             r'\def\num{%02d}' % episode,
             r'\begin{tikzpicture}',
             r'\node[shape=rectangle, fill=colext, minimum size=2cm] {};',
             r'\node[shape=circle, fill=colint, minimum size=1.5cm]',
             r'{\color{coltxt}\huge\num};',
             r'\end{tikzpicture}',
             r'\end{document}',
             ]
    doc = '\n'.join(lines)
    return doc


def palette_named(title_or_code):
    if all(c in string.digits for c in title_or_code):
        url = 'http://www.colourlovers.com/api/palette/{code}'.format(code=title_or_code)
        params={ 'format': 'json', }
    else:
        url = 'http://www.colourlovers.com/api/palettes'
        params={'keywords': title_or_code,
                'keywordExact': 1,
                'format': 'json',
                'numResults': 1
                }
    r = requests.get(url, params=params)
    res = r.json()
    return res[0]['colors']


def make_logo(params):
    colors = palette_named(params['<palette_name>'])
    extcolor = colors[int(params['<idx_ext>'])]
    intcolor = colors[int(params['<idx_int>'])]
    txtcolor = colors[int(params['<idx_txt>'])]
    ep_num = int(params['<ep_num>'])
    with open('temp.tex', 'w') as f:
        tex = tex_document(ep_num, extcolor, intcolor, txtcolor)
        f.write(tex)
    os.system('xelatex -halt-on-error temp')
    os.system('pdftoppm -png -scale-to 256 temp.pdf > temp.png')


def main():
    params = docopt.docopt(__doc__)
    make_logo(params)


if __name__ == '__main__':
    main()
